sudo: required
jdk: oraclejdk8

before_install:
  - mkdir $HOME/.wurst/
  - sudo apt-get install -y wine

install:
  - cd $HOME/.wurst
  - wget https://grill.wurstlang.org/hudson/job/WurstSetup/lastSuccessfulBuild/artifact/downloads/WurstSetup.jar
  - java -jar WurstSetup.jar install wurstscript

before_script: cd $TRAVIS_BUILD_DIR

script:
  - java -jar $HOME/.wurst/wurstscript.jar $HOME/.wurst/common.j $HOME/.wurst/blizzard.j ./ -runcompiletimefunctions -runtests
